"""Shared constants and defaults for AntiRaidVerify."""

from __future__ import annotations

VERIFY_CUSTOM_ID = "antiraidverify:verify"

DEFAULT_SCORE_THRESHOLD = 5
DEFAULT_ACCOUNT_AGE_DAYS = 7
DEFAULT_TIMEOUT_HOURS = 8
DEFAULT_TIMEOUT_ACTION = "kick"
DEFAULT_BAN_DURATION_HOURS = 0
DEFAULT_MASS_JOIN_THRESHOLD = 10
DEFAULT_MASS_JOIN_WINDOW_SECONDS = 60
DEFAULT_VERIFY_COOLDOWN_SECONDS = 30
DEFAULT_USERNAME_DIGIT_MIN = 4

DEFAULT_SPAM_USERNAME_PATTERNS: list[str] = [
    r"\d{5,}",
    r"^[a-zA-Z]{2,3}\d{4,}$",
    r"(.)\1{3,}",
    r"[il1|]{4,}",
]

# Embed colors
COLOR_SUSPICIOUS = 0xE67E22
COLOR_SUCCESS = 0x2ECC71
COLOR_TIMEOUT = 0xE74C3C
COLOR_ADMIN = 0x3498DB
COLOR_ERROR = 0x992D22
COLOR_INFO = 0x95A5A6

TIMEOUT_POLL_INTERVAL_SECONDS = 60
